apiVersion: v1
kind: ConfigMap
metadata:
  name: productcatalog-api-config
  namespace: microservices
data:
  RunMigrationsOnStartup: "true"
  Jwt__Issuer: "UserManagement.API"
  Jwt__Audience: "UserManagement.Clients"
  RabbitMq__HostName: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__ExchangeName: "microservices.events"
  Services__UserManagement__BaseUrl: "http://usermanagement-api:8081"
