apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-api
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagement-api
  template:
    metadata:
      labels:
        app: usermanagement-api
    spec:
      containers:
        - name: usermanagement-api
          image: usermanagement-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: usermanagement-api-config
            - secretRef:
                name: usermanagement-api-secret
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1"
