apiVersion: v1
kind: Secret
metadata:
  name: productcatalog-api-secret
  namespace: microservices
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=sql-server.microservices.svc.cluster.local,1433;Database=ProductCatalogDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
  Jwt__Key: "change-this-to-a-secure-secret-key-at-least-32-chars"
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"
