apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
  namespace: microservices
spec:
  serviceName: sql-server
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: MSSQL_SA_PASSWORD
            - name: MSSQL_MEMORY_LIMIT_MB
              value: "1200"
          resources:
            requests:
              memory: "900Mi"
              cpu: "250m"
            limits:
              memory: "1536Mi"
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: sql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
